name: Checkout Code

on:
  push:
    branches:
      - main
  

jobs:
  checkout:
    runs-on: rhel80  # Using a default runner with Docker support

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run in Docker
      run: pwd
