name: Checkout Code

on:
  push:
    branches:
      - main
      - feature-*
      - develop
  

jobs:
  checkout:
    runs-on: ubuntu-latest  # Using a default runner with Docker support

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run in Docker
      run: pwd && touch akhila.txt
